# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AFGitHubIssues' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON'
  # Pods for AFGitHubIssues

  target 'AFGitHubIssuesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AFGitHubIssuesUITests' do
    # Pods for testing
  end

end
